### ISSUE TITLE
Front end and Back end deployment 

### ISSUE THREAD

**Issue by JoshuaChou10** [AritroSaha10/ReliefExchange-ICS4U#10]

**Comment by AritroSaha10** [comment]
Just a small update on this for the future: this is a task that I'll only have to worry about once we have a final product that needs to be deployed. For now, we can just manage with running this on our computers.

**Comment by AritroSaha10** [comment]
Successfully deployed! Using Vercel for the frontend, Oracle Server & Docker for the backend. Now to just squash bugs.

Frontend: https://reliefexchange.aritrosaha.ca/
Backend: https://reliefexchange-backend.aritrosaha.ca/

**Comment by AritroSaha10** [comment]
Done 🎉🎉
