### ISSUE TITLE
Add CSS for donations page

### ISSUE THREAD

**Issue by JoshuaChou10** [AritroSaha10/ReliefExchange-ICS4U#12]

**Comment by AritroSaha10** [comment]
I have started to work on this since I'm not sure if Taha was able to, hence the assignment change.

**Comment by AritroSaha10** [comment]
Just a note, make sure to use react-markdown when displaying the description so that it sanitizes it before adding it to the DOM.

**Comment by AritroSaha10** [comment]
Donations ID page is completely done, had to rework the backend-frontend connection to use getStaticProps instead. This makes it significantly quicker as it caches the data on an edge server instead of the client pinging our backend every time. Taha is currently working on the donations index page.

**Comment by AritroSaha10** [comment]
Accidentally closed lol

**Comment by AritroSaha10** [comment]
I finished the search bar and backend for the donations index yesterday, just waiting on Taha to send over his code.

**Comment by AritroSaha10** [comment]
Finished in 21f17f102aa8221624b355573bf1f8ca8a5e738d
